---
title: Index
author: Abdullah Mahmood
date: last-modified
format:
    html:
        theme: cosmo
        css: ../quarto-style/style.css        
        highlight-style: atom-one        
        mainfont: Palatino
        fontcolor: black
        monobackgroundcolor: white
        monofont: Menlo, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace
        fontsize: 13pt
        linestretch: 1.4
        toc: true
        toc-location: right
        toc-depth: 5
        code-fold: true
        code-copy: true
        cap-location: bottom
        format-links: false
        embed-resources: true
        anchor-sections: true
        html-math-method:
            method: mathjax
            url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
---

## Pages:

### Models

#### Acquisition Models:

- [Depth-of-Repeat Model - Forecasting Aggregate Repeat-Buying](https://abdullahau.github.io/customer-analytics/DoR-Model)
- [Sales Forecast: Predicting Unit Sales Using Finite Mixture Model with Beta-Geometric Distribution](https://abdullahau.github.io/customer-analytics/Sales-Forecast-Finite-Mixture-Beta-Geometric)

#### Retention Models:

- [Beta-Geometric (BG) Model](https://abdullahau.github.io/customer-analytics/Beta-Geometric-Model)
- [Beta-discrete-Weibull (BdW) Model](https://abdullahau.github.io/customer-analytics/BdW-Model)
- [Discrete-Time, Contractual Setting Retention Model](https://abdullahau.github.io/customer-analytics/subscription-retention-model)

#### Purchasing Models:

- [NBD Model Variants - Overview](https://abdullahau.github.io/customer-analytics/NBD-Model)
- [BG/NBD Model](https://abdullahau.github.io/customer-analytics/BG-NBD-Model)
- [BG/NBD Model - Stan Implementation](https://abdullahau.github.io/customer-analytics/BG-NBD-Model-Stan)
- [NBD/OTB Model - NBD with One-Time Buyers](https://abdullahau.github.io/customer-analytics/NBD-OTB-Model)
- [BG/BB Model - Discrete-Time, Noncontractual Setting](https://abdullahau.github.io/customer-analytics/BG-BB-Model)

#### Spend Models:

- [Gamma-Gamma Model of Monetary Value](https://abdullahau.github.io/customer-analytics/gamma-gamma)

#### Combined CLV Models:

- [RFM and CLV: Using Iso-Value Curves for Customer Base Analysis](https://abdullahau.github.io/customer-analytics/RFM-and-CLV)

### Analaysis & Summaries

- [Analysing Buyer Behaviour Using Consumer Panel Data](https://abdullahau.github.io/customer-analytics/buyer-behavior-summary-panel-data)
- [Analysing Buyer Behaviour Using Transaction Logs](https://abdullahau.github.io/customer-analytics/buyer-behavior-summary-transaction-log)
- [Calculating Customer Acquisition Cost](https://abdullahau.github.io/customer-analytics/Customer-Acquisition-Cost)
- [RFM: Recency, Frequency, Monetary value Summary](https://abdullahau.github.io/customer-analytics/RFM-Summary)

### Data Preparation

- [CDNOW Data Set & Summaries](https://abdullahau.github.io/customer-analytics/CDNOW-Dataset)

## Source Files

Github Page: [https://github.com/abdullahau/customer-analytics](https://github.com/abdullahau/customer-analytics)

## Build from Source

Required Packages:

```
numpy
pandas
polars
matplotlib
altair
arviz
scipy
statsmodels
scikit-learn
scikit-optimize
Lifetimes
great-tables
ipykernel
quarto
stan
bridgestan
```

